public class Main {
    public static void main(String[] args) {
int bigStock = 2000000;
System.out.println("Большой склад вмещает " + bigStock + " кг ");
byte box = 127;
System.out.println("Коробочка вмещает " + box + " кг ");
short chest = 32767;
System.out.println("Сундук вмещает " + chest + " кг ");
long bigHangar = 11986536269565L;
System.out.println("Большой ангар вмещает " + bigHangar + " кг ");
float pieceOfCake = 2.15f;
System.out.println("Кусочек пирога весит " + pieceOfCake + " кг ");
double exactValue = 3.7896;
System.out.println("Точный вес продукта составляет " + exactValue + " кг ");
float secondPieceOfCake = 27.12f;
System.out.println("Второй КУСОЧЕК пирога весит " + secondPieceOfCake + " кг ");
long residents = 987678965549L;
System.out.println("Всего жителей в городе " + residents);
float a = 2.786f;
System.out.println(a);
short b = 569;
System.out.println(b);
short c = -159;
System.out.println(c);
short d = 27897;
System.out.println(d);
byte e = 67;
System.out.println(e);
short totalPepper = 480;
byte lyudaStudents = 23;
byte annaStudents = 27;
byte katyaStudents = 30;
byte totalStudents = (byte) (lyudaStudents + annaStudents + katyaStudents);
System.out.println("На каждого ученика рассчитано " + totalPepper / totalStudents + " листов бумаги");
byte performancePerMinute = 16 / 2;
System.out.println("За 1 минуту машина произвела " + performancePerMinute + " штук бутылок ");
short machineWork20 = (short) (performancePerMinute * 20);
System.out.println("За 20 минут машина произвела " + machineWork20 + " штук бутылок");
short machineWork1D = (short) (performancePerMinute * 24 * 60);
System.out.println("За сутки машина произвела " + machineWork1D + " штук бутылок");
int machineWork3D = 3 * machineWork1D;
System.out.println("За 3 дня машина произвела " + machineWork3D + " штук бутылок");
int machineWorkMonth = 10 * machineWork3D;
System.out.println("За месяц машина произвела " + machineWorkMonth + " штук бутылок");
int totalWhitePaintPerClass = 2;
int totalBrownPaintPerClass = 4;
int totalPaintJars = 120;
int paintJarsPerClass = totalWhitePaintPerClass + totalBrownPaintPerClass;
int totalClass = totalPaintJars / paintJarsPerClass;
int totalWhitePaint = totalClass * totalWhitePaintPerClass;
int totalBrownPaint = totalClass * totalBrownPaintPerClass;
System.out.println("В школе где " + totalClass + " классов, нужно " + totalWhitePaint + " банок белой краски и " + totalBrownPaint + " банок коричневой краски");
short banana = 5 * 80;
System.out.println("Банан - " + banana + " грамм");
short milk = 105 * 2;
System.out.println("Молоко - " + milk + " грамм");
short iceCream = 100 * 2;
System.out.println("Мороженое - " + iceCream + " грамм");
short eggs = 70 * 4;
System.out.println("Яйца - " + eggs + " грамм");
short totalGram = (short) (banana + milk + iceCream + eggs);
System.out.println("Получается завтрак на - " + totalGram + " грамм");
int grPerKg = 1000;
float weightKg = totalGram/(float)grPerKg;
System.out.println("Завтрак - " + weightKg + " кг");
short loseWeight = 7 * 1000;
int gramPerDay250 = 250;
int gramPerDay500 = 500;
short gram250 = (short) (loseWeight / gramPerDay250);
System.out.println(gram250 + " Дней потребуется для похудения");
short gram500 = (short) (loseWeight / gramPerDay500);
System.out.println(gram500 + " Дней потребуется для похудения");
short midMeaning = (short) (gram250 + gram500 / 2);
System.out.println(midMeaning + " Дней в среднем нужно для похудения");
int mashaMoney = 67760;
int denisMoney = 83690;
int krisMoney = 76230;
float percentIncrease = 0.10F;
int period = 12;
int mashaPromotion = (int) (mashaMoney * percentIncrease);
int mashaPromotionDif = mashaMoney + mashaPromotion;
int denisPromotion = (int) (denisMoney * percentIncrease);
int denisPromotionDif = denisMoney + denisPromotion;
int krisPromotion = (int) (krisMoney * percentIncrease);
int krisPromotionDif = krisMoney + krisPromotion;
int mashaYearMoney = mashaMoney * period;
int mashaYearMoneyWithPromotion = mashaPromotionDif * period;
int mashaDif = mashaYearMoneyWithPromotion - mashaYearMoney;
System.out.println ("Маша теперь получает " + mashaPromotionDif + " рублей в месяц." + " Годовой доход вырос на " + mashaDif + " рублей");
int denisYearMoney = denisMoney * period;
int denisYearMoneyWithPromotion = denisPromotionDif * period;
int denisDif = denisYearMoneyWithPromotion - denisYearMoney;
System.out.println("Денис теперь получает " + denisPromotionDif + " рублей в месяц." + " Годовой доход вырос на " + denisDif + " рублей");
int krisYearMoney = krisMoney * period;
int krisYearMoneyWithPromotion = krisPromotionDif * period;
int krisDif = krisYearMoneyWithPromotion - krisYearMoney;
System.out.println("Кристина теперь получает " + krisPromotionDif + " рублей в месяц." + " Годовой доход вырос на " + krisDif + " рублей");


    }
}