public class Main {
    public static void main(String[] args) {
int bigStock = 2000000;
System.out.println("Большой склад вмещает " + bigStock + " кг ");
byte box = 127;
System.out.println("Коробочка вмещает " + box + " кг ");
short chest = 32767;
System.out.println("Сундук вмещает " + chest + " кг ");
long bigHangar = 11986536269565L;
System.out.println("Большой ангар вмещает " + bigHangar + " кг ");
float pieceOfCake = 2.15f;
System.out.println("Кусочек пирога весит " + pieceOfCake + " кг ");
double exactValue = 3.7896;
System.out.println("Точный вес продукта составляет " + exactValue + " кг ");
float secondPieceOfCake = 27.12f;
System.out.println("Второй КУСОЧЕК пирога весит " + secondPieceOfCake + " кг ");
long residents = 987678965549L;
System.out.println("Всего жителей в городе " + residents);
float a = 2.786f;
System.out.println(a);
short b = 569;
System.out.println(b);
short c = -159;
System.out.println(c);
short d = 27897;
System.out.println(d);
byte e = 67;
System.out.println(e);
short totalPepper = 480;
byte lyudaStudents = 23;
byte annaStudents = 27;
byte katyaStudents = 30;
byte totalStudents = (byte) (lyudaStudents + annaStudents + katyaStudents);
System.out.println("На каждого ученика рассчитано " + totalPepper / totalStudents + " листов бумаги");
byte machineWork = 8;
System.out.println("За 1 минуту машина произвела " + machineWork + " штук бутылок ");
short machineWork20 = (short) (machineWork * 20);
System.out.println("За 20 минут машина произвела " + machineWork20 + " штук бутылок");
short machineWork1D = (short) (machineWork * 1140);
System.out.println("За сутки машина произвела " + machineWork1D + " штук бутылок");
int machineWork3D = machineWork * 4320;
System.out.println("За 3 дня машина произвела " + machineWork3D + " штук бутылок");
int machineWorkMonth = machineWork * 43200;
System.out.println("За месяц машина произвела " + machineWorkMonth + " штук бутылок");
int totalClass = 120 / 6;
byte totalWhitePaint = 20 * 2;
byte totalBrownPaint = 20 * 4;
System.out.println("В школе где " + totalClass + " классов, нужно " + totalWhitePaint + " банок белой краски и " + totalBrownPaint + " банок коричневой краски");
short banana = 5 * 80;
System.out.println("Банан - " + banana + " грамм");
short milk = 105 * 2;
System.out.println("Молоко - " + milk + " грамм");
short iceCream = 100 * 2;
System.out.println("Мороженое - " + iceCream + " грамм");
short eggs = 70 * 4;
System.out.println("Яйца - " + eggs + " грамм");
short totalGram = (short) (banana + milk + iceCream + eggs);
System.out.println("Получается завтрак на - " + totalGram + " грамм");
int grPerKg = 1000;
float weightKg = totalGram/(float)grPerKg;
System.out.println("Завтрак - " + weightKg + " кг");
short loseWeight = 7 * 1000;
short gram250 = (short) (loseWeight / 250);
System.out.println(gram250 + " Дней потребуется для похудения");
short gram500 = (short) (loseWeight / 500);
System.out.println(gram500 + " Дней потребуется для похудения");
short midMeaning = (short) (gram250 + gram500 / 2);
System.out.println(midMeaning + " Дней в среднем нужно для похудения");
int mashaMoney = 67760;
int denisMoney = 83690;
int krisMoney = 76230;
int mashaPromotion = (int) (mashaMoney * 0.10);
int mashaPromotionDif = mashaMoney + mashaPromotion;
int denisPromotion = (int) (denisMoney * 0.10);
int denisPromotionDif = denisMoney + denisPromotion;
int krisPromotion = (int) (krisMoney * 0.10);
int krisPromotionDif = krisMoney + krisPromotion;
int mashaYearMoney = mashaMoney * 12;
int mashaYearMoneyWithPromotion = mashaPromotionDif * 12;
int mashaDif = mashaYearMoneyWithPromotion - mashaYearMoney;
System.out.println ("Маша теперь получает " + mashaPromotionDif + " рублей в месяц." + " Годовой доход вырос на " + mashaDif + " рублей");
int denisYearMoney = (int) (denisMoney * 12);
int denisYearMoneyWithPromotion = (int) (denisPromotionDif * 12);
int denisDif = (int) (denisYearMoneyWithPromotion - denisYearMoney);
System.out.println("Денис теперь получает " + denisPromotionDif + " рублей в месяц." + " Годовой доход вырос на " + denisDif + " рублей");
int krisYearMoney = (int) (krisMoney * 12);
int krisYearMoneyWithPromotion = (int) (krisPromotionDif * 12);
int krisDif = (int)  (krisYearMoneyWithPromotion - krisYearMoney);
System.out.println("Кристина теперь получает " + krisPromotionDif + " рублей в месяц." + " Годовой доход вырос на " + krisDif + " рублей");

    }
}